tree_tests: tree_tests.cpp
	g++ -Wall -Werror -pedantic -g tree.cpp tree_tests.cpp -o tree_tests.exe

mergesort: mergesort.cpp
	g++ -Wall -Werror - pedantic -g mergesort.cpp -o mergesort.exe

clean:
	del tree_tests.exe mergesort.exe